# Generated by cpp11: do not edit by hand

check_ax_le_nx <- function(ax, age_group_type) {
  .Call(`_poputils_check_ax_le_nx`, ax, age_group_type)
}

lx_to_dx <- function(lx) {
  .Call(`_poputils_lx_to_dx`, lx)
}

lx_to_qx <- function(lx) {
  .Call(`_poputils_lx_to_qx`, lx)
}

mx_to_ex <- function(mx, age_group_type, sex, ax, method) {
  .Call(`_poputils_mx_to_ex`, mx, age_group_type, sex, ax, method)
}

mx_to_lx <- function(mx, age_group_type, sex, ax, method) {
  .Call(`_poputils_mx_to_lx`, mx, age_group_type, sex, ax, method)
}

mx_to_Lx <- function(mx, age_group_type, sex, ax, method) {
  .Call(`_poputils_mx_to_Lx`, mx, age_group_type, sex, ax, method)
}

qx_to_lx <- function(qx) {
  .Call(`_poputils_qx_to_lx`, qx)
}
