# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Calculate life expectancy from a matrix of 
#' mortality rates
#'
#' Calculate life expectancy.
#'
#' \describe{
#'   \item{\code{"const"}}{ Mortality rates are constant
#'         within each age interval; equivalently, the
#'         life table function \code{lx} is an exponential
#'         curve within each age interval.}
#'   \item{\code{"mid"}}{ On average, people die half way
#'         through each age interval; equivalently, the
#'         life table function \code{lx} is a straight
#'         line within each age interval. }
#'   \item{\code{"CD-Female"}, \code{"CD-Male"}}{ As for
#'         \code{"mid"}, except that the average age at
#'         which infants die (and, if \code{age} is
#'         \code{"lt"}, the average age at which
#'         children aged 1-4 die), is determined by
#'         formulas developed by Coale and Demeny, and
#'         reported in Preston et al (2001). }
#'   \item{\code{"HMD-Female"}, \code{"HMD-Male"}}{ The
#'         approach used in the Human Mortality Database.
#'         As for \code{"mid"}, except that the average
#'         age at which infants die is determined by
#'         formulas developed by Andreev and Kingkade (2015),
#'         and reported in Wilmoth et al (2019). }
#' }
#' 
#' 
#' |                      | \code{"lt"} | \code{"single"} | \code{"five"} |
#' |:---------------------|-------------|-----------------|---------------|
#' | \code{"const"}       | X           | X               | X             |
#' | \code{"mid"}         | X           | X               | X             |
#' | \code{"CD-Female"}   | X           | X               |               |
#' | \code{"CD-Male"}     | X           | X               |               |
#' | \code{"HMD-Female"}  |             | X               |               |
#' | \code{"HMD-Male"}    |             | X               |               |
#'
#'
#' The last age group is always assumed to be open.
#'
#' @param mx Mortality rates. A matrix of non-negative values.
#' Must have at least one column.
#' @param age Type of age groups used. Choices are
#' \code{"lt"}, \code{"single"}, and \code{"five"}.
#' @param method Name of method for converting mortality
#' rates to probabilities of dying. Choices are
#' \code{"const"}, \code{"mid"},
#' \code{"CD-Female"}, \code{"CD-Male"},
#' \code{"HMD-Female"}, and \code{"HMD-Male"}.
#'
#' @return A numeric vector with length \code{nrow(mx)}.
#'
#' @examples
#' mx <- matrix(c(0.010, 0.002, 0.070, 0.200,
#'                0.011, 0.003, 0.072, 0.210),
#'              nrow = 2)
#'
#' lifeexp(mx, age = "lt", method = "mid")
#' lifeexp(mx, age = "lt", method = "CD-Female")
#' lifeexp(mx, age = "single", method = "CD-Female")
#' lifeexp(mx, age = "single", method = "const")
#' @md
#'
#' @export
lifeexp <- function(mx, age, method) {
    .Call(`_poputils_lifeexp`, mx, age, method)
}

#' Calculate life expectancy based on
#' 'ax' and 5-year age groups
#'
#' Calculate life expectancy using an
#' ax-based method, with 5-year age groups.
#' In practice, the only ax-based method for calculating
#' life expectancy that works when all age groups
#' are 5-year is the "mid" method, ie the one
#' where  ax is 2.5 for all age groups except
#' the open age group.
#'
#' With this method, the probability of dying, qx,
#' can exceed 1. \code{lifeexp_ax_five}
#' adjusts the probability
#' downwards, with a warning.
#'
#' @param mx A matrix of mortality rates,
#' using 5-year age groups. 
#'
#' @return A vector of life expectancies,
#' with length equal to mx.nrow().
#'
#' @noRd
lifeexp_ax_five <- function(mx) {
    .Call(`_poputils_lifeexp_ax_five`, mx)
}

#' Calculate life expectancy based on
#' 'ax' and abridged life table age groups
#'
#' Calculate life expectancy using ax-based
#' methods with abridged life table age groups, ie
#' 0, 1-4, 5-9, ...., A+. 
#'
#' Argument \code{index_method} can be 1 (= "mid")
#' 2 (= "CD-Female") or 3 (= "CD-Male"). The
#' value for \code{index_method} affects
#' the way that a0 and a1 are calculated.
#' 'ax' equals 2.5 in all other age groups, apart from
#' A+.
#'
#' With this method, the probability of dying,
#' qx, can exceed 1.
#' \code{lifeexp_ax_lt} adjusts the estimated
#' probability downwards, with a warning.
#'
#' @param mx A matrix of mortality rates,
#' using life table age groups.
#' @param index_method Index number for method
#' for calculating 'a0' and 'a1'.
#'
#' @return A vector of life expectancies,
#' with length equal to mx.nrow().
#'
#' @noRd
lifeexp_ax_lt <- function(mx, method) {
    .Call(`_poputils_lifeexp_ax_lt`, mx, method)
}

#' Calculate life expectancy based on
#' 'ax' and single-year age groups
#'
#' Calculate life expectancy using ax-based
#' methods with single-year age groups.
#'
#' Argument \code{index_method} can be 1 (= "mid")
#' 2 (= "CD-Female"), 3 (= "CD-Male"),
#' 4 (= "HMD-Female"), 5 (= "HMD-Male").
#' value for \code{index_method} affects
#' the way that a0 is calculated.
#' 'ax' equals 0.5 in all other age groups, apart from
#' A+.
#'
#' With this method, the probability of dying,
#' qx, can exceed 1.
#' \code{lifeexp_ax_lt} adjusts the estimated
#' probability downwards, with a warning.
#'
#' @param mx A matrix of mortality rates,
#' using single-year age groups.
#' @param index_method Index number for method
#' for calculating 'a0'.
#'
#' @return A vector of life expectancies,
#' with length equal to mx.nrow().
#'
#' @noRd
lifeexp_ax_single <- function(mx, method) {
    .Call(`_poputils_lifeexp_ax_single`, mx, method)
}

#' Calculate life expectancy based on constant
#' mortality rates and 5-year age groups
#'
#' Calculate life expectancy using the assumption
#' of constant mortality rates within each
#' age group, and with 5-year age groups.
#'
#' @param mx A matrix of mortality rates,
#' using 5-year age groups.
#'
#' @return A vector of life expectancies,
#' with length equal to mx.nrow().
#'
#' @noRd
lifeexp_const_five <- function(mx) {
    .Call(`_poputils_lifeexp_const_five`, mx)
}

#' Calculate life expectancy based on constant
#' mortality rates and life table age groups
#'
#' Calculate life expectancy using the assumption
#' of constant mortality rates within each
#' age group, and with abridged life table age groups, ie
#' 0, 1-4, 5-9, ...., A+.
#'
#' @param mx A matrix of mortality rates,
#' using life table age groups.
#'
#' @return A vector of life expectancies,
#' with length equal to mx.nrow().
#'
#' @noRd
lifeexp_const_lt <- function(mx) {
    .Call(`_poputils_lifeexp_const_lt`, mx)
}

#' Calculate life expectancy based on constant
#' mortality rates and 1-year age groups
#'
#' Calculate life expectancy using the assumption
#' of constant mortality rates within each
#' age group, and with 1-year age groups.
#'
#' @param mx A matrix of mortality rates,
#' using 1-year age groups.
#'
#' @return A vector of life expectancies,
#' with length equal to mx.nrow().
#'
#' @noRd
lifeexp_const_single <- function(mx) {
    .Call(`_poputils_lifeexp_const_single`, mx)
}

