# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Calculate life expectancy from mortality rates
#'
#' Workhorse function for R function .lifeexp
#' 
#' @param mx Mortality rates.
#' @param age_groups Type of age groups used.
#' @param method Method for converting calculating
#' life expectancy.
#'
#' @noRd
le <- function(mx, age_groups, method) {
    .Call(`_poputils_le`, mx, age_groups, method)
}

#' Calculate life expectancy based on
#' 'ax' and 5-year age groups
#'
#' Calculate life expectancy using an
#' ax-based method, with 5-year age groups.
#' In practice, the only ax-based method for calculating
#' life expectancy that works when all age groups
#' are 5-year is the "mid" method, ie the one
#' where  ax is 2.5 for all age groups except
#' the open age group.
#'
#' With this method, the probability of dying, qx,
#' can exceed 1. \code{le_ax_five}
#' adjusts the probability
#' downwards.
#'
#' @param mx A matrix of mortality rates,
#' using 5-year age groups. 
#'
#' @return A vector of life expectancies,
#' with length equal to mx.nrow().
#'
#' @noRd
le_ax_five <- function(mx) {
    .Call(`_poputils_le_ax_five`, mx)
}

#' Calculate life expectancy based on
#' 'ax' and abridged life table age groups
#'
#' Calculate life expectancy using ax-based
#' methods with abridged life table age groups, ie
#' 0, 1-4, 5-9, ...., A+. 
#'
#' Argument \code{index_method} can be 1 (= "mid")
#' 2 (= "CD-Female") or 3 (= "CD-Male"). The
#' value for \code{index_method} affects
#' the way that a0 and a1 are calculated.
#' 'ax' equals 2.5 in all other age groups, apart from
#' A+.
#'
#' With this method, the probability of dying,
#' qx, can exceed 1.
#' \code{le_ax_lt} adjusts the estimated
#' probability downwards, with a warning.
#'
#' @param mx A matrix of mortality rates,
#' using life table age groups.
#' @param index_method Index number for method
#' for calculating 'a0' and 'a1'.
#'
#' @return A vector of life expectancies,
#' with length equal to mx.nrow().
#'
#' @noRd
le_ax_lt <- function(mx, method) {
    .Call(`_poputils_le_ax_lt`, mx, method)
}

#' Calculate life expectancy based on
#' 'ax' and single-year age groups
#'
#' Calculate life expectancy using ax-based
#' methods with single-year age groups.
#'
#' Argument \code{index_method} can be 1 (= "mid")
#' 2 (= "CD-Female"), 3 (= "CD-Male"),
#' 4 (= "HMD-Female"), 5 (= "HMD-Male").
#' value for \code{index_method} affects
#' the way that a0 is calculated.
#' 'ax' equals 0.5 in all other age groups, apart from
#' A+.
#'
#' With this method, the probability of dying,
#' qx, can exceed 1.
#' \code{le_ax_lt} adjusts the estimated
#' probability downwards, with a warning.
#'
#' @param mx A matrix of mortality rates,
#' using single-year age groups.
#' @param index_method Index number for method
#' for calculating 'a0'.
#'
#' @return A vector of life expectancies,
#' with length equal to mx.nrow().
#'
#' @noRd
le_ax_single <- function(mx, method) {
    .Call(`_poputils_le_ax_single`, mx, method)
}

#' Calculate life expectancy based on constant
#' mortality rates and 5-year age groups
#'
#' Calculate life expectancy using the assumption
#' of constant mortality rates within each
#' age group, and with 5-year age groups.
#'
#' @param mx A matrix of mortality rates,
#' using 5-year age groups.
#'
#' @return A vector of life expectancies,
#' with length equal to mx.nrow().
#'
#' @noRd
le_const_five <- function(mx) {
    .Call(`_poputils_le_const_five`, mx)
}

#' Calculate life expectancy based on constant
#' mortality rates and life table age groups
#'
#' Calculate life expectancy using the assumption
#' of constant mortality rates within each
#' age group, and with abridged life table age groups, ie
#' 0, 1-4, 5-9, ...., A+.
#'
#' @param mx A matrix of mortality rates,
#' using life table age groups.
#'
#' @return A vector of life expectancies,
#' with length equal to mx.nrow().
#'
#' @noRd
le_const_lt <- function(mx) {
    .Call(`_poputils_le_const_lt`, mx)
}

#' Calculate life expectancy based on constant
#' mortality rates and 1-year age groups
#'
#' Calculate life expectancy using the assumption
#' of constant mortality rates within each
#' age group, and with 1-year age groups.
#'
#' @param mx A matrix of mortality rates,
#' using 1-year age groups.
#'
#' @return A vector of life expectancies,
#' with length equal to mx.nrow().
#'
#' @noRd
le_const_single <- function(mx) {
    .Call(`_poputils_le_const_single`, mx)
}

